In [37]:
import numpy as np
from scipy.sparse import diags
from scipy.linalg import eigh
from math import ceil

In [47]:
class tree():
    def __init__(self):
        self.L = None
        return 
    
    def getL(self, n):
        A = diags([1, 1,1, 1], [-2,-1, 1, 2], shape=(n,n)).todense()
        D = np.diag([np.sum(i) for i in A])
        self.L = D - A
        return
    
    def evals(self, n, k):
        self.getL(n)
        return eigh(self.L, eigvals_only=True, eigvals=(k,k))
    
    def limit(self, k_, orders=[], limits=[], compare=False, top=12):
        if len(orders) > 0:
            vis = []
            for i in range(2,top):
                n = 2**i
                if k_==-1: k = n-1
                elif k_==0: k=ceil(n/2)-1
                else:k=k_
                res = self.evals(n, k)[0]
                for j in range(len(orders)):
                    res = res*(n**orders[j])
                    try:
                        res = limits[j] - res
                    except:
                        break
                vis.append(res)
        else:
            vis = []
            for i in range(2,12):
                n = 2**i
                if k_==-1: k = n-1
                elif k_==0: k=ceil(n/2)-1
                else:k=k_
                res = self.evals(n, k)
                vis.append(res[0])
        
        if compare:
            ratios = np.array(vis[:-1])/np.array(vis[1:])
            return vis, ratios
        else:
            return vis

# Limits for $\lambda_2$ of Tree

$14\pi^2-n^2(5\pi^2-n^2\lambda_2)\to 0$

In [3]:
T = tree()

print("Limit of lambda_2")
print(T.limit(1, compare=True))

print("\nLimit of n^2 * lambda_2")
print(T.limit(1, [2]))

print("\nLimit of 5*pi^2 - n^2 * lambda_2")
print(T.limit(1, [2],[5*np.pi**2], compare=True))

print("\nLimit of n^2(5*pi^2 - n^2 * lambda_2)")
print(T.limit(1, [2,2],[5*np.pi**2]))

print("\nLimit of 14*pi^2 - n^2(5*pi^2 - n^2 * lambda_2)")
print(T.limit(1, [2,2],[5*np.pi**2, 14*np.pi**2], compare=True, top=14))


Limit of lambda_2
([1.9999999999999998, 0.7186057604078513, 0.19006506010544735, 0.04804115374243324, 0.01203904671216353, 0.0030114318456859997, 0.0007529583558903144, 0.0001882457385898704, 4.7061815085207135e-05, 1.1765477426469395e-05], array([2.78316722, 3.78084094, 3.95629674, 3.990445  , 3.99778156,
       3.99946667, 3.99986933, 3.99996766, 3.99999196]))

Limit of n^2 * lambda_2
[31.999999999999996, 45.99076866610248, 48.65665538699452, 49.19414143225164, 49.31193533302182, 49.33929935971942, 49.34587881162764, 49.34749089690298, 49.34788981478616, 49.34798903175029]

Limit of 5*pi^2 - n^2 * lambda_2
([17.348022005446797, 3.357253339344311, 0.6913666184522711, 0.1538805731951527, 0.036086672424971766, 0.008722645727374356, 0.002143193819151179, 0.0005311085438108876, 0.00013219066063641094, 3.297369650567816e-05], array([5.16732586, 4.85596679, 4.49287785, 4.26419403, 4.13712462,
       4.06992856, 4.03532168, 4.01774635, 4.00897305]))

Limit of n^2(5*pi^2 - n^2 * lambda_2)
[2

$14\pi^2-n^2(5\pi^2-n^2\lambda_2)\to 0$

# Limits for $\lambda_3$ of Tree

$224\pi^2-n^2(20\pi^2-n^2\lambda_3)\to 0$

In [13]:
T = tree()

print("Limit of lambda_3")
print(T.limit(2, compare=True))

print("\nLimit of n^2 * lambda_3")
print(T.limit(2, [2]))

print("\nLimit of 20*pi^2 - n^2 * lambda_3")
print(T.limit(2, [2],[20*np.pi**2], compare=True))

print("\nLimit of n^2(20*pi^2 - n^2 * lambda_3)")
print(T.limit(2, [2,2],[20*np.pi**2],top=13))

print("\nLimit of 224*pi^2 - n^2(20*pi^2 - n^2 * lambda_3)")
print(T.limit(2, [2,2],[20*np.pi**2, 224*np.pi**2], compare=True, top=13))

Limit of lambda_3
([4.0, 2.267949192431123, 0.7280956399206235, 0.19036685500944087, 0.048050566547480696, 0.012039340466149717, 0.003011441021417559, 0.000752958642596769, 0.00018824574754938394, 4.706181536560277e-05], array([1.76370794, 3.11490561, 3.82469753, 3.96180251, 3.99112947,
       3.99786693, 3.99947733, 3.99987066, 3.99996783]))

Limit of n^2 * lambda_3
[64.0, 145.14874831559186, 186.39248381967963, 194.93565952966745, 196.81512057848093, 197.25255419739696, 197.35779877962113, 197.3835904048874, 197.3899729823428, 197.39156043520916]

Limit of 20*pi^2 - n^2 * lambda_3
([133.39208802178717, 52.243339706195314, 10.999604202107548, 2.456428492119727, 0.5769674433062448, 0.1395338243902131, 0.03428924216603946, 0.00849761689977413, 0.00211503944436231, 0.0005275865780163258], array([2.55328409, 4.74956542, 4.47788496, 4.25748198, 4.13496474,
       4.06931783, 4.03515981, 4.01771084, 4.00889547]))

Limit of n^2(20*pi^2 - n^2 * lambda_3)
[2134.273408348595, 3343.5737411965, 2

$224\pi^2-n^2(20\pi^2-n^2\lambda_3)\to 0$

# Limits for $\lambda_n$ of Tree

$n^2\left(-6.25 - \frac{3.75-n^2(6.25-\lambda_n)}{n^2}\right) \to \approx -201.142$

In [32]:
T = tree()

print("Limit of lambda_n")
print(T.limit(-1))

print("\nLimit of 6.25 - lambda_n")
print(T.limit(-1, [0],[6.25], compare=True))

print("\nLimit of n^2 * (6.25 - lambda_n)")
print(T.limit(-1, [0,2],[6.25], top=13))

print("\nLimit of 3.75 - n^2 * (6.25 - lambda_n)")
print(T.limit(2, [0,2],[6.25, 3.75], compare=True,top=13))

print("\nLimit of n^-2(3.75 - n^2 * (6.25 - lambda_n))")
print(T.limit(2, [0,2,-2],[6.25, 3.75],top=13))

print("\nLimit of -6.25 - n^-2(3.75 - n^2 * (6.25 - lambda_n))")
print(T.limit(2, [0,2,-2],[6.25, 3.75, -6.25],top=13, compare=True))

print("\nLimit of n^2(-6.25 - n^-2(3.75 - n^2 * (6.25 - lambda_n)))")
print(T.limit(2, [0,2,-2, 2],[6.25, 3.75, -6.25],top=14))

Limit of lambda_n
[4.0, 5.732050807568878, 6.103834431837829, 6.214441521668287, 6.2408917414982, 6.2477337532122235, 6.249436210693271, 6.249858627745026, 6.249964696741307, 6.24999117807158]

Limit of 6.25 - lambda_n
([2.25, 0.5179491924311224, 0.1461655681621714, 0.035558478331712884, 0.00910825850179986, 0.002266246787776538, 0.0005637893067289568, 0.00014137225497368178, 3.530325869327555e-05, 8.821928419777691e-06], array([4.34405543, 3.54357869, 4.1105687 , 3.90398212, 4.01909384,
       4.01966969, 3.98797704, 4.00451007, 4.00176209]))

Limit of n^2 * (6.25 - lambda_n)
[36.0, 33.14874831559183, 37.41838544951588, 36.41188181167399, 37.307426823372225, 37.1301873709308, 36.94849600578891, 37.059888407820836, 37.018149787560105, 37.00184965878725, 37.01031540334225]

Limit of 3.75 - n^2 * (6.25 - lambda_n)
([-32.25, -251.10125168440814, -1409.8575161803203, -6201.314340470332, -25399.43487942152, -102198.9974458026, -409398.8922012204, -1638198.8664095951, -6553398.860027018, -26

$n^2\left(-6.25 - \frac{3.75-n^2(6.25-\lambda_n)}{n^2}\right) \to \approx -201.142$

# Limits for $\lambda_{(n/2)}$ of Tree

$n(4.4-\lambda_{(n/2)})\to \approx 10.05$

In [52]:
T = tree()

print("Limit of lambda_(n/2)")
print(T.limit(0,top=13))

print("\nLimit of 4.5 - lambda_(n/2)")
print(T.limit(0, [0],[4.5], compare=True))

print("\nLimit of n(4.5 - lambda_(n/2))")
print(T.limit(0, [0,1],[4.5],top=13))

Limit of lambda_(n/2)
[1.9999999999999998, 3.2281237287624616, 3.9999999999999982, 4.224227102797177, 4.35633158373986, 4.425208676516482, 4.463717412067408, 4.4795379363953165, 4.490278244799742, 4.495436494706383]

Limit of 4.5 - lambda_(n/2)
([2.5, 1.2718762712375384, 0.5000000000000018, 0.27577289720282305, 0.14366841626014004, 0.07479132348351758, 0.036282587932592314, 0.0204620636046835, 0.009721755200257753, 0.004563505293616821], array([1.9656    , 2.54375254, 1.81308608, 1.91950955, 1.92092357,
       2.06135581, 1.77316368, 2.10477051, 2.13032627]))

Limit of n(4.5 - lambda_(n/2))
[10.0, 10.175010169900307, 8.000000000000028, 8.824732710490338, 9.194778640648963, 9.57328940589025, 9.288342510743632, 10.476576565597952, 9.95507732506394, 9.346058841327249, 10.079228124628571]


$n(4.4-\lambda_{(n/2)})\to \approx 10.05$

In [42]:
4.498/np.pi**2

0.45574268402323537

In [46]:
T.evals(4,1)

array([2.])

In [49]:
np.pi**2

9.869604401089358

In [53]:
2**12

4096

In [60]:
6000*(4.5 - T.evals(6000,3000-1))

array([10.04300658])

In [56]:
ceil(6000/2)-1

2999

In [57]:
3000-1

2999

In [59]:
4096*(4.5 - T.evals(4096,2048-1))

array([10.07922812])